// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provale.sql

package database

import (
	"context"
)

const getAllProvaleStats = `-- name: GetAllProvaleStats :many
SELECT id, tekst, usage_count 
FROM provale 
ORDER BY usage_count DESC
`

func (q *Queries) GetAllProvaleStats(ctx context.Context) ([]Provale, error) {
	rows, err := q.db.QueryContext(ctx, getAllProvaleStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provale
	for rows.Next() {
		var i Provale
		if err := rows.Scan(&i.ID, &i.Tekst, &i.UsageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeastUsedProvale = `-- name: GetLeastUsedProvale :many
SELECT id, tekst, usage_count
FROM provale
ORDER BY usage_count ASC
LIMIT 5
`

func (q *Queries) GetLeastUsedProvale(ctx context.Context) ([]Provale, error) {
	rows, err := q.db.QueryContext(ctx, getLeastUsedProvale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provale
	for rows.Next() {
		var i Provale
		if err := rows.Scan(&i.ID, &i.Tekst, &i.UsageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementProvalaUsage = `-- name: IncrementProvalaUsage :exec
UPDATE provale
SET usage_count = usage_count + 1
WHERE id = ?
`

func (q *Queries) IncrementProvalaUsage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementProvalaUsage, id)
	return err
}
